import postcss, { AtRule, type ChildNode, Declaration, Rule } from 'postcss'

export type CssRules = { [key: string]: string | CssRules }
export type CssVars = { light?: Record<string, string>; dark?: Record<string, string>; theme?: Record<string, string> }
export type ItemCss = { css?: CssRules; cssVars?: CssVars }

const GROUPS = ['light', 'dark', 'theme'] as const
type Group = (typeof GROUPS)[number]

const LIGHT = ':root, .light'
const HEADER =
  '/* Generated by scripts/build-registry.ts from packages/registry/registry.json. Edit the sources, not this file. */'

const clean = (text: string) => text.replace(/\s+/g, ' ').trim()

export const mergeRules = (target: CssRules, source: CssRules): CssRules => {
  for (const [key, value] of Object.entries(source)) {
    const existing = target[key]
    target[key] = typeof value === 'string' ? value : mergeRules(typeof existing === 'object' ? existing : {}, value)
  }
  return target
}

const keyOf = (node: Rule | AtRule) =>
  node instanceof Rule ? clean(node.selector) : `@${node.name}${node.params ? ` ${clean(node.params)}` : ''}`

const rulesOf = (nodes: ChildNode[]): CssRules => {
  const rules: CssRules = {}
  for (const node of nodes) {
    if (node instanceof Declaration) {
      rules[node.prop] = `${clean(node.value)}${node.important ? ' !important' : ''}`
    } else if (node instanceof Rule || node instanceof AtRule) {
      mergeRules(rules, { [keyOf(node)]: rulesOf(node.nodes ?? []) })
    }
  }
  return rules
}

const VARIABLE_BLOCKS: Record<string, Group | undefined> = { ':root': 'light', '.dark': 'dark' }

const groupOf = (node: ChildNode): Group | undefined => {
  if (node instanceof Rule) return VARIABLE_BLOCKS[clean(node.selector)]
  if (node instanceof AtRule && node.name === 'theme' && clean(node.params) === 'inline') return 'theme'
  return undefined
}

export const itemCssFromSource = (source: string): ItemCss => {
  const cssVars: CssVars = {}
  const css: CssRules = {}
  for (const node of postcss.parse(source).nodes) {
    const group = groupOf(node)
    if (!group) {
      mergeRules(css, rulesOf([node]))
      continue
    }
    const block = node as Rule | AtRule
    for (const child of block.nodes ?? []) {
      if (child instanceof Declaration && child.prop.startsWith('--')) {
        cssVars[group] = { ...cssVars[group], [child.prop.slice(2)]: clean(child.value) }
      } else {
        mergeRules(css, { [keyOf(block)]: rulesOf([child]) })
      }
    }
  }
  return {
    ...(Object.keys(cssVars).length > 0 ? { cssVars } : {}),
    ...(Object.keys(css).length > 0 ? { css } : {}),
  }
}

const leaves = (rules: CssRules, path: string[]): [string, string][] =>
  Object.entries(rules).flatMap(([key, value]) =>
    typeof value === 'string'
      ? [[[...path, key].join(' > '), value] as [string, string]]
      : leaves(value, [...path, key]),
  )

export const conflictsOf = (items: (ItemCss & { name: string })[]) => {
  const seen = new Map<string, { name: string; value: string }>()
  const conflicts: string[] = []
  for (const item of items) {
    const entries = [
      ...GROUPS.flatMap((group) =>
        Object.entries(item.cssVars?.[group] ?? {}).map(
          ([name, value]) => [`cssVars.${group} > --${name}`, value] as [string, string],
        ),
      ),
      ...leaves(item.css ?? {}, ['css']),
    ]
    for (const [key, value] of entries) {
      const previous = seen.get(key)
      if (previous && previous.value !== value) {
        conflicts.push(`${key}: "${previous.name}" declares ${previous.value}, "${item.name}" declares ${value}`)
      }
      seen.set(key, { name: item.name, value })
    }
  }
  return conflicts
}

const serialize = (rules: CssRules, depth = 0): string => {
  const pad = '  '.repeat(depth)
  return Object.entries(rules)
    .map(([key, body]) => {
      if (typeof body === 'string') return `${pad}${key}: ${body};`
      if (Object.keys(body).length === 0) return `${pad}${key};`
      return `${pad}${key} {\n${serialize(body, depth + 1)}\n${pad}}`
    })
    .join(depth === 0 ? '\n\n' : '\n')
}

const withLight = (rules: CssRules): CssRules =>
  Object.fromEntries(
    Object.entries(rules).map(([key, value]) => [
      key === ':root' ? LIGHT : key,
      typeof value === 'string' ? value : withLight(value),
    ]),
  )

const variables = (selector: string, vars: Record<string, string>): CssRules =>
  Object.keys(vars).length > 0
    ? { [selector]: Object.fromEntries(Object.entries(vars).map(([name, value]) => [`--${name}`, value])) }
    : {}

export const stylesheetOf = (items: ItemCss[]) => {
  const vars: Record<Group, Record<string, string>> = { light: {}, dark: {}, theme: {} }
  const css: CssRules = {}
  for (const item of items) {
    for (const group of GROUPS) Object.assign(vars[group], item.cssVars?.[group])
    mergeRules(css, item.css ?? {})
  }
  const entries = Object.entries(css)
  const sections = [
    Object.fromEntries(entries.filter(([key]) => key.startsWith('@import '))),
    variables(LIGHT, vars.light),
    variables('.dark', vars.dark),
    variables('@theme inline', vars.theme),
    withLight(Object.fromEntries(entries.filter(([key]) => !key.startsWith('@import ')))),
  ]
  return `${[HEADER, ...sections.map((section) => serialize(section)).filter(Boolean)].join('\n\n')}\n`
}
