import assert from 'node:assert/strict'
import { test } from 'node:test'

import { conflictsOf, itemCssFromSource, stylesheetOf } from './lib/registry-css.ts'

test('reads :root, .dark and @theme inline variables into cssVars and the rest into css', () => {
  const source = `@import "@kappa-ui/core/tailwind.css";

:root {
  --radius: 0.75rem;
}

.dark {
  color-scheme: dark;
  --background: oklch(0.145 0 0);
}

@supports (color: oklch(from red l c h)) {
  :root {
    --primary: oklch(from var(--brand) 0.48 c h);
  }
}

@theme inline {
  --radius-lg: var(--radius);
}
`
  assert.deepEqual(itemCssFromSource(source), {
    cssVars: {
      light: { radius: '0.75rem' },
      dark: { background: 'oklch(0.145 0 0)' },
      theme: { 'radius-lg': 'var(--radius)' },
    },
    css: {
      '@import "@kappa-ui/core/tailwind.css"': {},
      '.dark': { 'color-scheme': 'dark' },
      '@supports (color: oklch(from red l c h))': { ':root': { '--primary': 'oklch(from var(--brand) 0.48 c h)' } },
    },
  })
})

test('leaves out empty groups', () => {
  assert.deepEqual(itemCssFromSource(':root {\n  --a: 1px;\n}\n'), { cssVars: { light: { a: '1px' } } })
})

test('reports one variable or rule declared with two values', () => {
  assert.deepEqual(
    conflictsOf([
      { name: 'one', cssVars: { light: { a: '1px' } }, css: { html: { color: 'red' } } },
      { name: 'two', cssVars: { light: { a: '1px' } } },
      { name: 'three', cssVars: { light: { a: '2px' } }, css: { html: { color: 'blue' } } },
    ]),
    [
      'cssVars.light > --a: "two" declares 1px, "three" declares 2px',
      'css > html > color: "one" declares red, "three" declares blue',
    ],
  )
})

test('writes imports first, then the variables, then the merged rules, with :root also matching .light', () => {
  const css = stylesheetOf([
    {
      cssVars: { light: { a: '1px' }, dark: { a: '2px' }, theme: { 'size-a': 'var(--a)' } },
      css: { '@import "x.css"': {}, '@layer base': { ':root': { '--b': 'var(--a)' } } },
    },
    { css: { '@import "x.css"': {}, '@layer base': { button: { cursor: 'pointer' } } } },
  ])
  assert.equal(
    css,
    `/* Generated by scripts/build-registry.ts from packages/registry/registry.json. Edit the sources, not this file. */

@import "x.css";

:root, .light {
  --a: 1px;
}

.dark {
  --a: 2px;
}

@theme inline {
  --size-a: var(--a);
}

@layer base {
  :root, .light {
    --b: var(--a);
  }
  button {
    cursor: pointer;
  }
}
`,
  )
})
